version: "3.8"

services:

  app:
    build: .
    container_name: app
    volumes:
      - .:/var/www

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
